sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
before_script: npm install -g coveralls nyc
after_success:
  - nyc --reporter=lcov npm test
  - coveralls < coverage/lcov.info
