sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  allow_failures:
    - node_js: "4.0"
    - node_js: "4.1"
    - node_js: "4.2"
    - node_js: "4.3"
before_script: npm install -g coveralls nyc
after_success:
  - nyc --reporter=lcov npm test
  - coveralls < coverage/lcov.info
