sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
before_script: npm install -g coveralls nyc
after_success:
  - nyc --reporter=lcov npm test
  - coveralls < coverage/lcov.info
